hubmapconsortium/entity-api

docker/docker-compose.yml, docker/entity-api/Dockerfile, docker/entity-api/entrypoint.sh
This PR:
- de-elevates root to hubmap user (mapped with the host UID and GID) for running nginx, uwsgi and docker processes
- the docker-compose takes UID and GID as new environment variables for passing host user info to docker container
- internal ports changes to allow nginx run as non-root process
=> Docker non root

src/app.py, src/dataset.py
- added new API endpoint `/entity-access-level/<uuid>` to return the access level as string for a given entity
- this endpoint calls the `dataset. get_entity_access_level()`
- improved error handling
- also added this new endpoint in gateway (in a separate branch now) and the auth requires HuBMAP-Read group.
@shirey @cborromeo please review and merge if all looks good. I've tested and it works with the gateway on DEV. One issue I noticed is that in the DEV version of neo4j, many of the entity nodes don't have the `data_access_level` attribute at this point since it's newly added.
=> Entity access level zhou

src/app.py, src/dataset.py
- added existence check for a given uuid before making a cypher call to get data_access_level
- return a default data_access_level as 'protected' when the attribute in metadata node is missing
=> Entity access level enhancement zhou

src/schema/schema_manager.py
Will also need to run the Cypher query to remove the `hubmap_base_id` property from Neo4j:
````
MATCH (n:Sample)
WHERE n.hubmap_base_id IS NOT NULL
REMOVE n.hubmap_base_id
RETURN count(n)
````
=> Remove hubmap_base_id when generating multiple samples

src/schema/provenance_schema.yaml
To address  https://github.com/hubmapconsortium/entity-api/issues/152
- Add `lab_dataset_id` for Dataset
- `Dataset.title` is no longer required on create
> copy existing values of Dataset.title to lab_dataset_id
Will need to execute this Cypher query in Neo4j:
````
MATCH (n:Dataset) 
WHERE n.title IS NOT NULL
SET n.lab_dataset_id=n.title
RETURN n.title, n.lab_dataset_id
````
Will also need to trigger a reindex to get this new filed into ES. The ingest-ui displays the table view by pulling information from search-api.
=> Dataset.lab_dataset_id

src/app.py
added the ability to chose to include or not include the full dataset for each revision in the list.
=> Added functionality to either include or

entity-api-spec.yaml, src/app.py
Added validation that checks that when a new dataset is created and points to a previous dataset as a previous revision, make sure that the previous dataset is published. If its not published, throws a bad_request_error.
=> Derek furst/validate new entity revisions

entity-api-spec.yaml, src/app.py
Per request from John Conroy:
- change output to use `uuid` instead of `dataset_uuid`
- provide a second, not specific dataset route `/entities/<id>/revisions`
=> change revisions method to not specify dataset type

entity-api-spec.yaml, src/schema/provenance_schema.yaml
Added db_gap url to provenance schema. Added db_gap to entity api spec. 
Also added sub_status and retraction_reason to the api spec as they were 
missing. Removed a duplicate description in the entity api spec.
=> Added db_gap url to provenance schema. Added db_gap to entity api spec.

src/app.py, src/app_neo4j_queries.py, src/requirements.txt, src/schema/schema_manager.py
Include sample information with provenance info to support the files-api creating file info documents.
Form complete uuid-api call "in code" from a configured base URL, replacing a configured complete URL.
=> Include Samples in prov info to support files-api

entity-api-spec.yaml, src/app.py, src/app_neo4j_queries.py
Implemented endpoint `datasets/paired-dataset` which takes a dataset id (hubmap_id or uuid) and a target data type, and will search for paired datasets of that data_type who a first sample ancestor with the given dataset. Optionally, search depth query
parameter sets the max number of generations beneath the sample ancestor to search for the paired dataset. Added accompanying function in app_neo4j_queries.
=> Derek furst/identify paired datasets

src/app_neo4j_queries.py
Fixed a bug caused by an "AND" where a "WHERE" should be in the optional
revision_of match in get_prov_info in app_neo4j_queries.py
=> Fixed a bug caused by an "AND" where a "WHERE" should be in the optional

src/schema/provenance_schema.yaml, src/schema/schema_validators.py
changed title from immutable to mutable and changed the language in the published status error message to indicate whether the entity is a dataset or a publication.
=> changed title from immutable to mutable and changed the language in the

src/app.py, src/uwsgi.ini
To accommodate c5.18xlarge -> c5.4xlarge
=> 32x8 -> 16x16 for EC2 PROD VM downgrade

src/app.py, src/schema/provenance_schema.yaml, src/schema/schema_triggers.py, src/schema/schema_validators.py
Added property creation_action to datasets and publications. This property is transient and immutable, so it won't be saved in the
database within the dataset/publication node itself, however the trigger method for the activity node with this property has been updated to grab this value if its in the json. If this field isn't present, it defaults to the existing value. Validator verifies that the property is only 'Central Process', 'Lab Process', or 'Multi-assay Split'.
=> Derek furst/add creation action

src/schema/provenance_schema.yaml, src/schema/schema_validators.py
Following merged PR #576 for TEST
=> Derek furst/add assigned to group name ingest task

src/schema/provenance_schema.yaml, src/schema/schema_triggers.py
Generate dataset_type='Publication' for Publication entities, and prohibit dataset_type from being specified on the request.
=> Automatically set dataset_type on Publication entities

entity-api-spec.yaml, src/app.py
changed siblings path from /siblings/<id> to /entities/<id>/siblings
=> Derek furst/update siblings

entity-api-spec.yaml, src/app.py, src/app_neo4j_queries.py
Endpoint to return 'samples', 'organs', and 'donors' uuids of dataset id given.
Issue: https://github.com/hubmapconsortium/entity-api/issues/604
=> Dataset sample and donor endpoints

src/app.py, src/schema/provenance_schema.yaml, src/schema/schema_manager.py
converted hubmapid to uuid before running schema_manager.entity_instanceof()
=> Derek furst/hubma id in instanceof

src/schema/provenance_schema.yaml, src/schema/schema_validators.py
Initial commit of changes supporting Multi-Assay Dataset tracking for entity-api #635. Added superseded_associated_processed_component_uuids and new_associated_multi_assay_uuid attributes to Datasets.
=> Initial commit of changes supporting Multi-Assay Dataset tracking

.github/workflows/python-app.yml, src/app.py, src/instance/app.cfg.example, src/schema/provenance_schema.yaml, src/schema/schema_constants.py, src/schema/schema_manager.py, src/schema/schema_triggers.py, src/schema/schema_validators.py
Changed the status property in provenance schema yaml. Now, its after update trigger method is update_status, which calls set status history, and then calls a new function sync_component_dataset_status. this works by creating new PUT calls to entity on each of the component datasets, updating their status to whatever the multi-assay dataset was. A new validator was also created that disallows directly updating the status of component datasets.
=> Derek furst/sync component datasets

src/app.py
Fixed typo which will cause exception.
=> Correction to editing mistake noticed before PROD deployment

src/app.py, src/schema/provenance_schema.yaml
Initial changes for search-api/issues/753. Remove search-api's neo4j-to-es-attributes.json and replace with indexed: indicators on attributes in entity-api's provenance_schema.yaml.
=> Remove search-api's neo4j-to-es-attributes.json and replace with indexed: indicators on attributes in entity-api's provenance_schema.yaml

src/app.py, src/schema/provenance_schema.yaml, src/schema/schema_validators.py
Removed the ability to include multiple previous revision id's when creating or updating an entity. 
Added validator that sees if a provided previous revision already has a revision itself and raises a value error if it does. 
Still allow previous_revision_uuid value to be a list or a string, if its a list, its just constrained to a single entry for the sake of compatibility. 
Left any underlying schema queries or other methods intact in case we need to use them later, just removed their uses in app.py and the provenance schema. 
Commented out the endpoint GET multi-revisions rather than deleting in case we need to add it back later.
=> Disabled multiple revisions

src/app.py, src/schema/schema_neo4j_queries.py
added GET endpoints /entities/<id>/collections and /entities/<id>/uploads and accompanying schema query methods.
=> added endpoints entities/<id>/collections

src/app.py
Added validator to confirm json body for constraints endpoint matches expected format. 
Specific values and fields are validated later on, this function confirms that the request body is a json list, where each entry in the list is a json object representing a constraint. Each constraint can only have the keys "ancestors" or "descendants". Ancestors and descendants values must be dictionaries or lists of dictionaries.
=> Derek furst/constraints

src/app.py, src/instance/app.cfg.example
Introduce usage of S3 for large responses, replacing error message when a response was too large for AWS Gateway to return. Requires corresponding changes to hubmap-commons.
=> Introduce usage of S3 for large responses

src/app.py, src/schema/schema_manager.py, src/schema/schema_triggers.py
reworked get_organ_types such that it is only called once during the initialization of schema_manager. Created a global variable inside schema triggers and a quick setter function inside app.py to set that value after initialization of schema manager but before the value is fetched in schema_triggers
=> Reworked get_organ_types 

src/app.py, src/schema/schema_manager.py, src/schema/schema_triggers.py
Following merged PR #725 for TEST
=> Derek furst/initialize get organ types

src/app.py
Fixed a bug where datasets within a public collection were not being filtered for excluded fields in get_entity_by_id
=> Fixed a bug where datasets within a public collection were not being filtered for excluded fields in get_entity_by_id

src/schema/schema_manager.py
Replace `/valueset` call to ontology-api with `/dataset-type` usage.
=> Use Ontology API dataset_type support, like ingest-ui.

src/app_neo4j_queries.py, src/requirements.txt, src/schema/schema_constants.py, src/schema/schema_neo4j_queries.py
modified omitted fields to not include metadata. Modified /ancestors /parents /children and /descendants to remove items from omitted fields from result
=> Derek furst/remove offending fields

src/dev_entity_worker.py, src/requirements.txt
Fix authorization problems to get correct field exclusion for public responses, except for known direct_ancestor problem.
=> Correct field exclusion for public responses, except for direct_ancestor problem

src/dev_entity_worker.py
Fix so /prov-metadata endpoint checks the <ID> is for a Dataset entity before checking authorization levels appropriate for access to whatever entity_type <ID> is for.
=> Verify Dataset <ID> passed to /prov-metadata before auth checks

entity-api-spec.yaml
Smart API YAML revisions for [entity-api#777](https://github.com/hubmapconsortium/entity-api/issues/777). Correct errors reported in editor at smart-api.info. Use security defined in `securitySchemas` section.
=> Correct Smart API YAML errors and use security schema

src/schema/schema_neo4j_queries.py, src/schema/schema_triggers.py
Initial release for entity-api#257.  Revised Dataset title generation.
=> Revised Dataset title generation

entity-api-spec.yaml, src/schema/provenance_schema.yaml, src/schema/schema_constants.py, src/schema/schema_validators.py
Following merged PR #867 #869 for TEST
=> Derek furst/priority project list

src/app.py, src/schema/schema_validators.py
Following merged PR #879 for TEST and PROD
=> Fire drill fix for entity-level validator call

src/schema/provenance_schema.yaml
added error_message field for uploads. changed indexed to false for dataset.
=> Derek furst/error message
