README.md, docker/docker-compose.dev.yml, docker/docker-compose.localhost.yml, docker/docker-compose.prod.yml, docker/docker-compose.test.yml, docker/docker-compose.yml
Added localhost to replace the old dev mode, and the new dev mode is for AWS/PSC deployment.
=> Deploy options zhou

src/app.py
@cborromeo please give a simple review
@yuanzhou  please deploy to DEV when Chuck gives the okay
=> made both collections calls available for consortium/public data without an auth token

src/app.py
I would like to merge the public_provenance_graph_call into 1.6 for testing
=> Public provenance graph call

src/app.py
for deployment to dev/test/stage
=> add new collection attributes and only send collections with doi_registered attribute

src/app.py
=> for collection redirect use standard http error responses

src/app.py
=> Added a few attributes

src/app.py, src/file_upload_helper.py, src/requirements.txt, src/schema/provenance_schema.yaml
- fixed import errors with urllib3
- added dataset.contributors and dataset.antibodies attributes
=> added dataset.contributors and dataset.antibodies attributes and fixed imort errors

src/app.py, src/schema/provenance_schema.yaml, src/schema/schema_manager.py, src/schema/schema_neo4j_queries.py, src/schema/schema_triggers.py
- added revision properties and linkage via trigger methods 
- do not response with empty string/dict/list on entity query
=> Dataset version zhou

src/app.py, src/schema/provenance_schema.yaml, src/schema/schema_manager.py, src/schema/schema_triggers.py
added updated_peripherally functionality, new property in the provenance .yaml file.
This should be a temporary measure.
=> Fix file updates deletes/adds/description change

src/app.py
Add support to the `status` filtering in query string for dataset only
=> Support status result filtering for Dataset

src/app.py, src/instance/app.cfg.example, src/schema/provenance_schema.yaml
The https://github.com/hubmapconsortium/ingest-api/pull/41 will need this change. 
The dataset redirection functionality added via https://github.com/hubmapconsortium/gateway/pull/89
=> DOI changes

src/schema/provenance_schema.yaml, src/schema/schema_validators.py
That isn’t needed until the Uploads stuff is released, but it won’t hurt anything now
=> changed Upload state Submitted to Reorganized and added Processing state

src/schema/provenance_schema.yaml
Quick fix to the missing Collection.description bug
=> Add collection description

src/app.py, src/schema/schema_manager.py, src/schema/schema_neo4j_queries.py, src/schema/schema_triggers.py
To address issue hubmapconsortium/ingest-api#89
Script to fix the above datasets: hubmapconsortium/manual-data-ingest#43
=> One activity node between entity node and parents

src/app.py, src/app_neo4j_queries.py
Following the merged PR #229 but for TEST
=> Derek furst/datasets feature revisions

entity-api-spec.yaml, src/app.py
Following merged PR #242 but for TEST
=> Derek furst/validate new entity revisions

entity-api-spec.yaml
- updated /datasets/<id>/retract open-api spec to pass syntax check and added request schema
- updated /datasets/<id>/revisions open-api spec to pass syntax check and added response schema
=> updated docs

src/app.py, src/app_neo4j_queries.py
Fixed bug where using inconsistent capitalization could 
allow an unaccepted argument. Added documentation to 
method validate_organ_code
=> Fixed bug where using inconsistent capitalization could

src/app.py, src/app_neo4j_queries.py
Changed the name of dataset_lab_id to lab_id_or_name. Added code that converts organ codes and data type codes to their
respective descriptions. Added processed dataset uuid, hubmap_id, status, and portal url fields
=> Derek furst/prov info

src/app_neo4j_queries.py
Following merged PR #293 but for TEST
=> Derek furst/prov info fix

docker/docker-compose.dev.yml, docker/docker-compose.localhost.yml, docker/docker-compose.prod.yml, docker/docker-compose.stage.yml, docker/docker-compose.test.yml, docker/docker-compose.yml
To work with gateway localhost build
=> Use the same nginx conf for localhost

src/app.py, src/app_neo4j_queries.py
Following merged PR #300 but for TEST
=> Derek furst/prov info no token

src/schema/provenance_schema.yaml, src/schema/schema_neo4j_queries.py, src/schema/schema_triggers.py
Still need to use Collection.datasets but exclusing time-consuming triggers
=> Back to use Collection.datasets

src/app.py
Following merged PR #325 but for TEST. To avoid exception when there's no token needed to access a published dataset:
```
[2022-03-29 14:57:55,422] ERROR in schema_manager: No Authorization header
NoneType: None
[2022-03-29 14:57:55,422] ERROR in app: No Authorization header
Traceback (most recent call last):
File "./app.py", line 3002, in user_in_hubmap_read_group
user_info = schema_manager.get_user_info(request)
File "./schema/schema_manager.py", line 1020, in get_user_info
raise Exception(msg)
Exception: No Authorization header
```
=> Add Authorization header check

entity-api-spec.yaml, src/app.py, src/app_neo4j_queries.py
This is the implementation of samples/prov-info. Also fixed a number of indentation errors introduced in the entity-api spec yaml.
=> Derek furst/prov info samples

src/app.py
Fixed a bug in samples/prov-info where organ_submission_id and
organ_hubmap_id would show up as null if the sample was of specimen type
"organ". Also removed a reference to organ_has_metadata which is no longer
used.
=> Fixed a bug in samples/prov-info where organ_submission_id and

src/app.py, src/schema/schema_manager.py
Following merged PR #364  #366 will test on TEST then publish the docker image to dockerhub for PROD release.
=> v2.1.1 release

entity-api-spec.yaml, src/app.py, src/app_neo4j_queries.py
=> Added endpoint datasets/unpublished to app.py. Added method in

src/app.py, src/app_neo4j_queries.py
Changed samples/prov-info (branch name incorrect) to accommodate users without a token, or without hubmap-read-group
membership.
=> Derek furst/datasets prov info public

entity-api-spec.yaml, src/schema/provenance_schema.yaml
Added dbgap_study_url to entity-api-spec.yaml and provenance_schema.yaml
=> Added dbgap_study_url to entity-api-spec.yaml and provenance_schema.yaml

entity-api-spec.yaml, src/app.py, src/schema/schema_manager.py, src/schema/schema_neo4j_queries.py, test/entity_instanceof_test.py
This https://github.com/hubmapconsortium/entity-api/issues/464 is used by https://github.com/hubmapconsortium/entity-api/issues/465.
=> Entity instanceof

entity-api-spec.yaml, src/schema/provenance_schema.yaml
Following merged PR #477 for TEST
=> Add Publication.omap_doi field

entity-api-spec.yaml, src/schema/provenance_schema.yaml, src/schema/schema_neo4j_queries.py, src/schema/schema_triggers.py
Added associated collection property to publications. Also fixed some properties in the entity api spec being in the wrong place
=> Derek furst/associated collection

entity-api-spec.yaml, src/app.py, src/schema/provenance_schema.yaml, src/schema/schema_neo4j_queries.py, src/schema/schema_triggers.py
Added property associated_collection_uuid for publications. can now use
post/put to create publication with associated_collection and update it.
=> Added property associated_collection_uuid for publications. can now use

src/schema/schema_validators.py
Removed multi-assay split from validator since this won't be part of a normal POST request.
=> removed multi-assay split from validator

src/app.py, src/schema/provenance_schema.yaml, src/schema/schema_triggers.py, src/schema/schema_validators.py
Following merged PR #538 #541 for TEST
Note:
Removed "multi-assay split" from validator, since there will be a specialized new endpoint to handle the multi-assay creation
=> Derek furst/add creation action

src/app.py
Fixed a bug in a group uuid exception handler where a reference is made to json_data_dict rather than the first json_data_dict in json_data_dict_list (json_data_dict[0] and json_data_dict[i] where appropriate).
=> Fixed a bug in a group uuid exception handler where a reference is made

entity-api-spec.yaml
dataset_link_abs_dir as a required field
=> Updated entity api spec entry for datasets/components to include

src/app_neo4j_queries.py
Following merged PR #559 for TEST
=> Derek furst/update derived queries

entity-api-spec.yaml, src/app.py, src/app_neo4j_queries.py
Following merged PR #562 for TEST
=> Derek furst/get multi revision

src/schema/provenance_schema.yaml
Issue: https://github.com/hubmapconsortium/entity-api/issues/551
Also for Publication (see comment on issue).
This adds to code already merged to dev-integrate previously from this branch.
=> Expose Creation Action; Also for Publication

src/schema/provenance_schema.yaml
Added field dataset_types to publications as well as datasets
=> Added field dataset_types to publications as well as datasets

src/schema/provenance_schema.yaml, src/schema/schema_validators.py
Following merged PR #607 for TEST
=> Added validator validate_not_invalid_creation_action

entity-api-spec.yaml, src/app.py, src/app_neo4j_queries.py, src/schema/schema_neo4j_queries.py
Following merged PR #606 for TEST
=> Derek furst/tuplets

entity-api-spec.yaml, src/app.py
=> Derek furst/update siblings

entity-api-spec.yaml, src/app.py, src/app_neo4j_queries.py
Following merged PR #612 for TEST
=> Dataset sample and donor endpoints

src/schema/provenance_schema.yaml, src/schema/schema_manager.py
Following merged PR #616 #624 for TEST
=> Derek furst/generalize sublcassing

src/app.py, src/schema/provenance_schema.yaml, src/schema/schema_manager.py
changed `id` to `id.strip()` in get_hubmap_ids and entity_instanceof
=> Derek furst/fix whitespace error

src/app.py, src/schema/schema_manager.py
Following merged PR #627 for TEST
=> changed `id` to `id.strip()` in get_hubmap_ids and entity_instanceof

src/app.py
Following merged PR #628 for TEST
=> Derek furst/hubma id in instanceof

src/app.py, src/schema/provenance_schema.yaml, src/schema/schema_manager.py, src/schema/schema_validators.py
Issue: https://github.com/hubmapconsortium/entity-api/issues/634
=> Upload and dataset status add incomplete

src/schema/provenance_schema.yaml, src/schema/schema_validators.py
Following merged PR #637 for TEST
=> Added incomplete to schema_validators for dataset and upload status

src/schema/schema_neo4j_queries.py
Modified some queries to explicitly define a label in a neo4j query match to help performance.
=> Derek furst/optimize queries

src/schema/schema_neo4j_queries.py
Following merged PR #657 for TEST
=> Modified some queries to explicitly define a label

src/app.py, src/app_neo4j_queries.py
Added constraint to /components endpoint. If any of the direct ancestors provided already has component children, Bad_request_error
=> added constraint to /components endpoint

src/app.py, src/app_neo4j_queries.py
Following merged PR #663 for TEST
=> Derek furst/limit component dataset

src/schema/provenance_schema.yaml
Following merged PR #670 for TEST
=> Add group_uuid and group_name for Collection

src/app.py, src/schema/provenance_schema.yaml, src/schema/schema_validators.py
Following merged PR #671 for TEST
=> Derek furst/disable multi revision

src/app.py, src/schema/provenance_schema.yaml
Following merged PR #676 for TEST
=> Derek furst/add epicollection

entity-api-spec.yaml, src/app.py, src/schema/schema_neo4j_queries.py
Following merged PR #686 for TEST
=> added endpoints entities/<id>/collections

src/schema/schema_neo4j_queries.py
Initial commit to establish all relationships in Neo4j from an Activity node to ancestors in a single Cypher query.
=> Establish all relationshipsto ancestors in a single query

src/schema/provenance_schema.yaml, src/schema/schema_validators.py
Following merged PR #712 for TEST
=> Derek furst/validate entityid not in ancestor

entity-api-spec.yaml, src/app.py, src/app_neo4j_queries.py, src/schema/schema_constants.py, src/schema/schema_validators.py
Fixed comments from https://github.com/hubmapconsortium/entity-api/pull/713#discussion_r1704330192
=> Bulk updating of entries endpoints

src/app.py
Found by Joe during his testing.
=> X-Application -> X-Hubmap-Application

src/schema/schema_manager.py
Following merged PR #757 for TEST
=> Use Ontology API dataset_type support, like ingest-ui.

src/schema/provenance_schema.yaml, src/schema/schema_validators.py
added new fields uploads.intended_dataset_type, and uploads.intended_organ, as well as a new validator to accommodate intended_dataset_type
=> Derek furst/add intended types

entity-api-spec.yaml, src/schema/provenance_schema.yaml
updated ingest_dataset_type and ingest_organ provenance to make required on create. Also added entries for entity-api-schema.yaml for these values
=> updated ingest_dataset_type and ingest_organ provenance to make required on create. Also added entries for entity-api-schema.yaml for these values

entity-api-spec.yaml, src/schema/provenance_schema.yaml
Following merged PR #764 for TEST
=> Derek furst/reorganize metadata

src/schema/schema_neo4j_queries.py
Moved key removal to the actual queries
=> Derek furst/remove offending fields

src/schema/provenance_schema.yaml
Following merged PR #812 for TEST
=> changed sample.direct_ancestor to be immutable

entity-api-spec.yaml
=> Fixes and tweaks

src/schema/schema_validators.py
Add module resolution to Exception subclass usage.
=> Add module resolution to Exception subclass usage.

src/schema/schema_triggers.py
Add in missed special case for title when Dataset is a "Publication [ancillary]" from code review.
=> Add in missed special case for title when Dataset is a "Publication [ancillary]" from code review.

src/schema/provenance_schema.yaml
Following merged PR #856 for TEST
=> added rui_exemption field to provenance schema.

src/app.py
Noticed this during debugging. Following merged PR #885 for TEST
=> Fix missing f-string in log message
